Update NPM package dependencies
symfony/webpack-encore pull request #1258
Opened 2024-02-01 16:13 UTC by abozhinov

Hello, 
I have dependency errors because using newest postcss, less, stylus loaders and for that we need to allow them in the package.json file. This PR will not break anything and it's pretty safe to merge it.

2024-02-01 17:40 UTC, weaverryan commented
Can you also run `yarn install` and commit the updated `yarn.lock` file? That may be related to the broken tests.

2024-02-02 09:10 UTC, stof requested changes

2024-02-02 09:10 UTC, stof commented on package.json
> +    "stylus": "^0.60.0 || ^0.62.0",
reducing the range of a peer dependency is a BC break. So you should not remove support for version 0.58

2024-02-02 09:42 UTC, abozhinov commented
I've update the package.json and yarn.lock

2024-02-02 15:25 UTC, weaverryan commented
Tests still failing - I think we actually need to go into the 3 `yarn-pnp-*` directories here - https://github.com/symfony/webpack-encore/tree/main/test_apps -and run `yarn install` in each and commit that updated lock file. I know, annoying - but we test a lot of different situations.

2024-02-05 08:17 UTC, vinceAmstoutz commented
@abozhinov Do y ou need any help?

2024-02-05 08:30 UTC, abozhinov commented
I run yarn install on each yarn-pnp-* directory but didn't help.

2024-02-05 08:44 UTC, abozhinov commented
I don't know why the yarn.lock files was changed... I've recreate it with the newest packages ...
➤ YN0028: The lockfile would have been modified by this install, which is explicitly forbidden.

2024-02-08 12:17 UTC, karpilin commented
@abozhinov this is because of last weeks yarn 4.1 release. I'll make separate PR to update the test_app setups.

Meanwhile, I updated the lockfiles and I've made PR into your fork https://github.com/abozhinov/webpack-encore/pull/1

2024-02-26 09:37 UTC, karpilin commented
@stof @weaverryan is there anything that needs correcting before this PR can be merged in?

2024-03-26 09:11 UTC, vinceAmstoutz commented
@stof @weaverryan ?

2024-05-01 15:34 UTC, vinceAmstoutz commented
@fabpot @nicolas-grekas ?

2024-06-14 12:19 UTC, rugbymauri commented
Works for me

```
/var/www $ npm list
www@ /var/www
+-- @babel/core@7.24.7
+-- @babel/preset-env@7.24.7
+-- @hotwired/stimulus@3.2.2
+-- @hotwired/turbo@8.0.4
+-- @symfony/stimulus-bridge@3.2.2
+-- @symfony/ux-autocomplete@npm:assets@1.0.0 -> ./vendor/symfony/ux-autocomplete/assets
+-- @symfony/ux-dropzone@npm:assets@1.1.0 -> ./vendor/symfony/ux-dropzone/assets
+-- @symfony/ux-live-component@npm:assets@1.0.0 -> ./vendor/symfony/ux-live-component/assets
+-- @symfony/ux-turbo@npm:assets@0.1.0 -> ./vendor/symfony/ux-turbo/assets
+-- @symfony/webpack-encore@4.6.1 (git+ssh://git@github.com/abozhinov/webpack-encore.git#8cb9590417074245f90a5db51ca03f7d448cabbf)
+-- @tailwindcss/forms@0.5.7
+-- @zackad/prettier-plugin-twig-melody@0.6.0
+-- autoprefixer@10.4.19
+-- core-js@3.37.1
+-- file-loader@6.2.0
+-- postcss-loader@8.1.1
+-- postcss@8.4.38
+-- prettier@3.3.2
+-- quill@2.0.2
+-- regenerator-runtime@0.14.1
+-- sass-loader@14.2.1
+-- sass@1.77.5
+-- stimulus-textarea-autogrow@4.1.0
+-- tailwindcss-stimulus-components@5.0.2
+-- tailwindcss@3.4.4
+-- tom-select@2.3.1
+-- webpack-cli@5.1.4
+-- webpack-notifier@1.15.0
`-- webpack@5.92.0


```

```
/var/www $ composer show
araise/definition-toolbox                      dev-main ef6068c  Definitions and more
bamarni/composer-bin-plugin                    1.8.2             No conflicts for your bin dependencies
behat/mink                                     1.11.0            Browser controller/emulator abstraction for PHP
brick/math                                     0.12.1            Arbitrary-precision arithmetic library
clue/ndjson-react                              1.3.0             Streaming newline-delimited JSON (NDJSON) parser and encoder for ReactPHP.
composer/pcre                                  3.1.4             PCRE wrapping library that offers type-safe preg_* replacements.
composer/semver                                3.4.0             Semver library that offers utilities, version constraint parsing and validation.
composer/xdebug-handler                        3.0.5             Restarts a process without Xdebug.
dbrekelmans/bdi                                1.3.0             PHAR distribution of dbrekelmans/browser-driver-installer.
dealerdirect/phpcodesniffer-composer-installer 1.0.0             PHP_CodeSniffer Standards Composer Installer Plugin
doctrine/cache                                 2.2.0             PHP Doctrine Cache library is a popular cache implementation that supports many different dr...
doctrine/collections                           2.2.2             PHP Doctrine Collections library that adds additional functionality on top of PHP arrays.
doctrine/data-fixtures                         1.7.0             Data Fixtures for all Doctrine Object Managers
doctrine/dbal                                  4.0.3             Powerful PHP database abstraction layer (DBAL) with many features for database schema intros...
doctrine/deprecations                          1.1.3             A small layer on top of trigger_error(E_USER_DEPRECATED) or PSR-3 logging with options to di...
doctrine/doctrine-bundle                       2.12.0            Symfony DoctrineBundle
doctrine/doctrine-fixtures-bundle              3.6.1             Symfony DoctrineFixturesBundle
doctrine/doctrine-migrations-bundle            3.3.1             Symfony DoctrineMigrationsBundle
doctrine/event-manager                         2.0.1             The Doctrine Event Manager is a simple PHP event system that was built to be used with the v...
doctrine/inflector                             2.0.10            PHP Doctrine Inflector is a small library that can perform string manipulations with regard ...
doctrine/instantiator                          2.0.0             A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                                 3.0.1             PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.
doctrine/migrations                            3.7.4             PHP Doctrine Migrations project offer additional functionality on top of the database abstra...
doctrine/orm                                   3.2.0             Object-Relational-Mapper for PHP
doctrine/persistence                           3.3.2             The Doctrine Persistence project is a set of shared interfaces and functionality that the di...
doctrine/sql-formatter                         1.4.0             a PHP SQL highlighting library
egulias/email-validator                        4.0.2             A library for validating emails against several RFCs
evenement/evenement                            3.0.2             Événement is a very simple event dispatching library for PHP
fakerphp/faker                                 1.23.1            Faker is a PHP library that generates fake data for you.
fidry/cpu-core-counter                         1.1.0             Tiny utility to get the number of CPU cores.
friendsofphp/php-cs-fixer                      3.58.1            A tool to automatically fix PHP code style
guzzlehttp/guzzle                              7.8.1             Guzzle is a PHP HTTP client library
guzzlehttp/promises                            2.0.2             Guzzle promises library
guzzlehttp/psr7                                2.6.2             PSR-7 message implementation that also provides common utility methods
jms/metadata                                   2.8.0             Class/method/property metadata management in PHP
knpuniversity/oauth2-client-bundle             2.18.1            Integration with league/oauth2-client to provide services
kubawerlos/php-cs-fixer-custom-fixers          3.21.0            A set of custom fixers for PHP CS Fixer
league/flysystem                               3.28.0            File storage abstraction for PHP
league/flysystem-bundle                        3.3.5             Symfony bundle integrating Flysystem into Symfony 5.4+ applications
league/flysystem-local                         3.28.0            Local filesystem adapter for Flysystem.
league/mime-type-detection                     1.15.0            Mime-type detection for Flysystem
league/oauth2-client                           2.7.0             OAuth 2.0 Client Library
league/oauth2-google                           4.0.1             Google OAuth 2.0 Client Provider for The PHP League OAuth2-Client
masterminds/html5                              2.9.0             An HTML5 parser and serializer.
monolog/monolog                                3.6.0             Sends your logs to files, sockets, inboxes, databases and various web services
myclabs/deep-copy                              1.12.0            Create deep copies (clones) of your objects
nikic/php-parser                               5.0.2             A PHP parser written in PHP
paragonie/random_compat                        9.99.100          PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
patchlevel/event-sourcing                      3.0.0             A lightweight but also all-inclusive event sourcing library with a focus on developer experi...
patchlevel/event-sourcing-bundle               3.0.x-dev 8975876 symfony bundle for patchlevel/event-sourcing
patchlevel/hydrator                            1.3.2             Hydrator
patchlevel/worker                              1.2.0             Gives the opportunity to build a stable worker that terminates properly when limits are exce...
phar-io/manifest                               2.0.4             Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                                3.2.1             Library for handling version information and constraints
php-webdriver/webdriver                        1.15.1            A PHP client for Selenium WebDriver. Previously facebook/webdriver.
phpdocumentor/reflection-common                2.2.0             Common reflection clas [...]

2024-06-15 16:41 UTC, garak commented
What about eslint? See #1267

2024-06-17 08:20 UTC, rugbymauri commented
@garak #1267 is still an issue

2024-06-22 16:50 UTC, melroy89 commented
Oopsy daisy

2024-08-19 08:07 UTC, closed without merging

2024-08-22 21:40 UTC, Kocal commented
Hi everyone, and sorry for the big delay!

Just to let you know, very soon a new version will be tagged with a lot of dependencies updates (see https://github.com/symfony/webpack-encore/milestone/3)