These changes allow empty public path in webpack.config.js
symfony/webpack-encore pull request #264
Opened 2018-02-13 10:35 UTC by stoccc

This allows empty publicPath in webpack.config.js
Provided a functional test.
See https://github.com/symfony/webpack-encore/issues/26#issuecomment-362560685

I'm new to webpack/encore/nodejs/git, so I hope I didn't make any mistake :)

2018-02-13 11:09 UTC, stoccc commented
@weaverryan I think I'll need some help with the functional test...

2018-02-13 14:10 UTC, stoccc commented
It seems that we have some problems using javascript `require.ensure`: the file path is not translated to the client according to the information stored in manifest.json.
Is there any config that we can edit so that the reference is generated properly?

2018-02-14 14:09 UTC, weaverryan requested changes
Hey @stoccc!

Thanks for starting this! Ok, about the `require.ensure` call... this is Webpack's responsibility to resolve this path correctly: it does not read from our `manifest.json`. file. Actually, it basically just uses the final `publicPath` config key to figure out the path to any code split files. So... this is a real problem: I'm not sure if relative paths *can* work with code-splitting. Since Webpack uses `publicPath` to find these files, if you use a relative path, then it will try to request a different file based on the URL of your page - e.g. http://example.com/foo versus http://example.com/foo/bar.

I found this with some quick research: https://stackoverflow.com/questions/36675286/webpack-code-splitting-relative-url

If this is correct, it confirms my believe.... because the solution they're suggesting is to override the publicPath at runtime... which is the only time we know the true path.

Can you research this a bit more? It may be that relative paths will simply *not* work with code splitting (unless the user does this workaround at runtime (more on this: https://webpack.js.org/guides/public-path/#on-the-fly).

2018-02-14 14:09 UTC, weaverryan commented on test/functional.js
> +            config.addEntry('main', './js/code_splitting');
I think we should also include an entry that loads a CSS file normally (i.e. without code splitting) that includes a path to an image or a font. Then, after running webpack, we can manually check the contents of the final CSS file to make sure that the path to that image is correct. As I understand it, THAT is the biggest problem we're having with relative paths: the paths to images/fonts in CSS files was being generated incorrectly.

Unfortunately, the `assertResourcesLoadedCorrectly` method you're using below works for JS only - that's why we need to test the contents of the file.

2026-09-07 11:46 UTC, Kocal commented
Closing this one. It never quite got finished, the functional test was still open when the PR stalled back in 2018, and the codebase has changed a lot since then. Thanks for giving it a shot, @stoccc.

2026-09-07 11:46 UTC, closed without merging