feat: add Encore.when()
symfony/webpack-encore pull request #963
Opened 2021-04-15 06:44 UTC by Kocal

2021-04-15 08:11 UTC, stof requested changes

2021-04-15 08:11 UTC, stof commented on index.js
> +     * @param {function} callback
should be `function(Encore): void`

2021-04-22 23:46 UTC, weaverryan approved these changes

2021-04-22 23:46 UTC, weaverryan commented on index.js
> +     * Use to conditionally configure or enable features only in when the first parameter results to "true".
```suggestion
     * Use to conditionally configure or enable features only when the first parameter results to "true".
```

2021-04-22 23:46 UTC, weaverryan commented on index.js
> +     *     .when(process.argv.includes('--analyze'), (Encore) => Encore.addPlugin(new BundleAnalyzerPlugin()))
Cool examples!

2021-04-22 23:47 UTC, weaverryan commented
This is very cool - thank you @Kocal!

2021-04-22 23:47 UTC, merged

2021-04-22 23:48 UTC, weaverryan commented on index.js
> +     * Use to conditionally configure or enable features only in when the first parameter results to "true".
Updated at sha: d0741010efcd47212bc632bb8ffa2021e5c724a5